### ISSUE TITLE
HTTP Call Failed

### ISSUE THREAD

**Issue by lingtze1** [aperepel/nifi-api-deploy#36]
Hi Andrew,

I get [ERROR] HTTP call failed. Status code: HTTP/1.1 404 Not Found: The specified res
ource could not be found.
Caught: java.lang.AssertionError: Terminated script execution. Expression: null
java.lang.AssertionError: Terminated script execution. Expression: null

I did changes according to documentation, which is the nifi.url. Attached my yml file. 

C:\Users\limcheh\Documents\GitHub\nifi-api-deploy>groovy NiFiDeploy.groovy --fil
e nifi-deploy.yml --debug
Loading Process Groups from NiFi
2016/11/17 13:09:31:500 SGT [DEBUG] BasicClientConnectionManager - Get connectio
n for route {}->http://127.0.0.1:9091
2016/11/17 13:09:31:527 SGT [DEBUG] DefaultClientConnectionOperator - Connecting
 to 127.0.0.1:9091
2016/11/17 13:09:31:560 SGT [DEBUG] RequestAddCookies - CookieSpec selected: bes
t-match
2016/11/17 13:09:31:581 SGT [DEBUG] RequestAuthCache - Auth cache not set in the
 context
2016/11/17 13:09:31:584 SGT [DEBUG] RequestTargetAuthentication - Target auth st
ate: UNCHALLENGED
2016/11/17 13:09:31:590 SGT [DEBUG] RequestProxyAuthentication - Proxy auth stat
e: UNCHALLENGED
2016/11/17 13:09:31:592 SGT [DEBUG] DefaultHttpClient - Attempt 1 to execute req
uest
2016/11/17 13:09:31:597 SGT [DEBUG] DefaultClientConnection - Sending request: G
ET /nifi-api/controller/process-groups/root/process-group-references HTTP/1.1
2016/11/17 13:09:31:603 SGT [DEBUG] wire - >> "GET /nifi-api/controller/process-
groups/root/process-group-references HTTP/1.1[\r][\n]"
2016/11/17 13:09:31:609 SGT [DEBUG] wire - >> "Accept: */*[\r][\n]"
2016/11/17 13:09:31:611 SGT [DEBUG] wire - >> "Host: 127.0.0.1:9091[\r][\n]"
2016/11/17 13:09:31:613 SGT [DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
2016/11/17 13:09:31:615 SGT [DEBUG] wire - >> "[\r][\n]"
2016/11/17 13:09:31:617 SGT [DEBUG] headers - >> GET /nifi-api/controller/proces
s-groups/root/process-group-references HTTP/1.1
2016/11/17 13:09:31:621 SGT [DEBUG] headers - >> Accept: */*
2016/11/17 13:09:31:625 SGT [DEBUG] headers - >> Host: 127.0.0.1:9091
2016/11/17 13:09:31:627 SGT [DEBUG] headers - >> Connection: Keep-Alive
2016/11/17 13:09:31:632 SGT [DEBUG] wire - << "HTTP/1.1 404 Not Found[\r][\n]"
2016/11/17 13:09:31:637 SGT [DEBUG] wire - << "Date: Thu, 17 Nov 2016 05:09:31 G
MT[\r][\n]"
2016/11/17 13:09:31:640 SGT [DEBUG] wire - << "Content-Type: text/plain[\r][\n]"

2016/11/17 13:09:31:644 SGT [DEBUG] wire - << "Transfer-Encoding: chunked[\r][\n
]"
2016/11/17 13:09:31:648 SGT [DEBUG] wire - << "Server: Jetty(9.3.9.v20160517)[\r
][\n]"
2016/11/17 13:09:31:652 SGT [DEBUG] wire - << "[\r][\n]"
2016/11/17 13:09:31:656 SGT [DEBUG] DefaultClientConnection - Receiving response
: HTTP/1.1 404 Not Found
2016/11/17 13:09:31:661 SGT [DEBUG] headers - << HTTP/1.1 404 Not Found
2016/11/17 13:09:31:663 SGT [DEBUG] headers - << Date: Thu, 17 Nov 2016 05:09:31
 GMT
2016/11/17 13:09:31:667 SGT [DEBUG] headers - << Content-Type: text/plain
2016/11/17 13:09:31:669 SGT [DEBUG] headers - << Transfer-Encoding: chunked
2016/11/17 13:09:31:671 SGT [DEBUG] headers - << Server: Jetty(9.3.9.v20160517)
2016/11/17 13:09:31:681 SGT [DEBUG] DefaultHttpClient - Connection can be kept a
live indefinitely
2016/11/17 13:09:31:696 SGT [DEBUG] wire - << "2A[\r][\n]"
2016/11/17 13:09:31:697 SGT [DEBUG] wire - << "The specified resource could not
be found."
2016/11/17 13:09:31:701 SGT [DEBUG] wire - << "[\r][\n]"
2016/11/17 13:09:31:703 SGT [DEBUG] wire - << "0[\r][\n]"
2016/11/17 13:09:31:706 SGT [DEBUG] wire - << "[\r][\n]"
2016/11/17 13:09:31:709 SGT [DEBUG] BasicClientConnectionManager - Releasing con
nection org.apache.http.impl.conn.ManagedClientConnectionImpl@2fab4aff
2016/11/17 13:09:31:714 SGT [DEBUG] BasicClientConnectionManager - Connection ca
n be kept alive indefinitely
[ERROR] HTTP call failed. Status code: HTTP/1.1 404 Not Found: The specified res
ource could not be found.
Caught: java.lang.AssertionError: Terminated script execution. Expression: null
java.lang.AssertionError: Terminated script execution. Expression: null
        at NiFiDeploy$_run_closure2.doCall(NiFiDeploy.groovy:575)
        at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:1070)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:1044)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.RESTClient.get(RESTClient.java:119)
        at groovyx.net.http.RESTClient$get.call(Unknown Source)
        at NiFiDeploy.loadProcessGroups(NiFiDeploy.groovy:240)
        at NiFiDeploy.run(NiFiDeploy.groovy:588)

[nifi-deploy.txt](https://github.com/aperepel/nifi-api-deploy/files/596568/nifi-deploy.txt)

Regards,
Yih

**Comment by lingtze1** [comment]
OK just found out that it is not for NiFi 1.0.
Do you have 1 for 1.0 or I need to customize it?

**Comment by akpuvvada** [comment]
I am also facing the same issue. Is this resolved?

**Comment by akpuvvada** [comment]
I am using 1.1.2 version
